# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b0eecaa6876e0e27d3987061f589a57b633d553819b2d8849291c8e40c1673595310d4a58dae3a88c1557ed9b441cdcf237736119505e408defc8c9239ab28f

test:
  secret_key_base: d0e9115a3134e69968b97324e0129668237353a60a86fc665ffc1336c9b25e82ed8ee392be0bc808bbfe1461498bb432040880ae6c7009564b0e4019819d8df3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
